### ISSUE TITLE
Call CoinMarketList.sort failed because it is sorting an UnmodifiableList

### ISSUE THREAD

**Issue by qingjinlyc** [Camphul/CoinMarketCap-API#4]
When I invoke CoinMarketList.sort() in my code, I saw exception:

```
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableList.sort(Collections.java:1331)
	at com.lucadev.coinmarketcap.model.CoinMarketList.sort(CoinMarketList.java:133)
```

Then I found what it does in sort:

`
@Override
    public void sort(Comparator<? super CoinMarket> comparator) {
        marketList.sort(comparator);
 }`

However `marketList` is an UnmodifiableList as it is instantiated by `this.marketList = Collections.unmodifiableList(new ArrayList<>(markets));`

**Comment by Camphul** [comment]
I thought about the UnmodifiableList before implementing it since the CoinMarket data won't change. However as you said you might want to sort it. 

Still deciding on this since you could also create a modifiable list from the existing unmodifiable list. However, this would not contain the custom get methods.

Any more arguments on why I should remove the unmodifiable list wrapper? I'll gladly do so if really needed.

**Comment by Camphul** [comment]
@qingjinlyc I understand why this wouldn't work but as I said what would be a good reason to remove the unmodifiable part(since you won't be adding markets either way)?

**Comment by qingjinlyc** [comment]
@Camphul Well, that's right although it doesn't look like a strong reason. 

However, you expose an interface called `addAll` which will definitely fail is a little bit wierd in my point of view.

**Comment by Camphul** [comment]
But the add methods cannot be made private since the class implements a List. I'll close this issue until other people report it again.
